### ISSUE TITLE
Sign In Modal does not redirect to warpcast app

### ISSUE THREAD

**Issue by gendev1** [neynarxyz/siwn#2]
Have setup wownar-react-native, tested on both android and ios,
when clicked on Sign in with Neynar, it does not redirect to warpcast, even if the app is present, only thing it returns is app download page

**Comment by Shreyaschorge** [comment]
@gendev1 Thanks for reporting

Please upgrade @neynar/react-native-signin to latest version i.e 0.2.5

Fixed in f14f3ee2364f02725d1cd5e48d42b5596b58a2b1
